name: floreat.nu
favicon: null
layout_spectrum: 0.2760859210975468
typography_spectrum: 0.7005881736986339
title: Florish
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#47443f'
    - '#7991ad'
    - '#c8d6e1'
    - '#4b6a86'
  brandStrength: 0.47533542942255735
  lightness: 0.33022086950950325
  saturation: 0.9154171927366406
  rhythmicContrast: 0.8479199635330588
purpose: []
